version: '3.8'
services:
  backend:
    build:
      context: ./liton-backend
      dockerfile: Dockerfile
    container_name: liton-backend
    restart: always
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=liton_db
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - database

  frontend:
    build:
      context: ./liton-frontend
      dockerfile: Dockerfile
    container_name: liton-frontend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - backend

  database:
    image: postgres:14-alpine
    container_name: liton-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: liton_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
